export const PROF_LOADING = "PROF_LOADING";
export const PROF_LOADED = "PROF_LOADED";
export const PROF_AUTH_ERROR = "PROF_AUTH_ERROR";
export const PROF_LOGIN_SUCCESS = "PROF_LOGIN_SUCCESS";
export const PROF_LOGIN_FAIL = "PROF_LOGIN_FAIL";
export const PROF_LOGOUT_SUCCESS = "PROF_LOGOUT_SUCCESS";

export const PROF_EDIT_PROFILE = "PROF_EDIT_PROFILE";
export const PROF_EDIT_PROFILE_FAIL = "PROF_EDIT_PROFILE_FAIL";
export const PROF_EDIT_PROFILE_PICTURE = "PROF_EDIT_PROFILE_PICTURE";
export const PROF_EDIT_PROFILE_PICTURE_FAIL = "PROF_EDIT_PROFILE_PICTURE_FAIL";
export const PROF_EDIT_PASS = "PROF_EDIT_PASS";
export const PROF_EDIT_PASS_FAIL = "PROF_EDIT_PASS_FAIL";

export const ETUDIANT_BY_NIVEAU_FILIERE =      "ETUDIANT_BY_NIVEAU_FILIERE";
export const ETUDIANT_BY_NIVEAU_FILIERE_FAIL = "ETUDIANT_BY_NIVEAU_FILIERE_FAIL";

export const AJOUTER_NOTE = "AJOUTER_NOTE";
export const AJOUTER_NOTE_FAIL = "AJOUTER_NOTE_FAIL";

export const LIST_NOTE="LIST_NOTE";
export const LIST_NOTE_FAIL="LIST_NOTE_FAIL";

export const MODIFIER_NOTE="MODIFIER_NOTE";
export const MODIFIER_NOTE_FAIL="MODIFIER_NOTE_FAIL";

export const ADD_DOCUMENT="ADD_DOCUMENT";
export const ADD_DOCUMENT_FAIL="ADD_DOCUMENT_FAIL";

export const LIST_DOCUMENT="LIST_DOCUMENT";
export const LIST_DOCUMENT_FAIL="LIST_DOCUMENT_FAIL";

export const MODIFIER_DOCUMENT="MODIFIER_DOCUMENT";
export const MODIFIER_DOCUMENT_FAIL="MODIFIER_DOCUMENT_FAIL";

export const DELETE_DOCUMENT="DELETE_DOCUMENT";
export const DELETE_DOCUMENT_FAIL="DELETE_DOCUMENT_FAIL";

