export const PROF_LOADING = "PROF_LOADING";
export const PROF_LOADED = "PROF_LOADED";
export const PROF_AUTH_ERROR = "PROF_AUTH_ERROR";
export const PROF_LOGIN_SUCCESS = "PROF_LOGIN_SUCCESS";
export const PROF_LOGIN_FAIL = "PROF_LOGIN_FAIL";
export const PROF_LOGOUT_SUCCESS = "PROF_LOGOUT_SUCCESS";