export const ETUDIANT_LOADING = "ETUDIANT_LOADING";
export const ETUDIANT_LOADED = "ETUDIANT_LOADED";
export const ETUDIANT_AUTH_ERROR = "ETUDIANT_AUTH_ERROR";
export const ETUDIANT_LOGIN_SUCCESS = "ETUDIANT_LOGIN_SUCCESS";
export const ETUDIANT_LOGIN_FAIL = "ETUDIANT_LOGIN_FAIL";
export const ETUDIANT_LOGOUT_SUCCESS = "ETUDIANT_LOGOUT_SUCCESS";

export const ETUDIANT_EDIT_PROFILE = "ETUDIANT_EDIT_PROFILE";
export const ETUDIANT_EDIT_PROFILE_FAIL = "ETUDIANT_EDIT_PROFILE_FAIL";
export const ETUDIANT_EDIT_PROFILE_PICTURE = "ETUDIANT_EDIT_PROFILE_PICTURE";
export const ETUDIANT_EDIT_PROFILE_PICTURE_FAIL = "ETUDIANT_EDIT_PROFILE_PICTURE_FAIL";

export const LIST_NOTE="LIST_NOTE";
export const LIST_NOTE_FAIL="LIST_NOTE_FAIL";

export const LIST_DOCUMENT="LIST_DOCUMENT";
export const LIST_DOCUMENT_FAIL="LIST_DOCUMENT_FAIL";
