export const ETUDIANT_LOADING = "ETUDIANT_LOADING";
export const ETUDIANT_LOADED = "ETUDIANT_LOADED";
export const ETUDIANT_AUTH_ERROR = "ETUDIANT_AUTH_ERROR";
export const ETUDIANT_LOGIN_SUCCESS = "ETUDIANT_LOGIN_SUCCESS";
export const ETUDIANT_LOGIN_FAIL = "ETUDIANT_LOGIN_FAIL";
export const ETUDIANT_LOGOUT_SUCCESS = "ETUDIANT_LOGOUT_SUCCESS";