export const ADMIN_LOADING = "ADMIN_LOADING";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const ADMIN_AUTH_ERROR = "AUTH_ERROR";
export const ADMIN_LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "LOGIN_FAIL";
export const ADMIN_LOGOUT_SUCCESS = "LOGOUT_SUCCESS";